### ISSUE TITLE
installation / running error : stringi.so

### ISSUE THREAD

**Issue by SoloveyMaria** [SoloveyMaria/community#1]
Hi, I am trying to install the community environment on the server, as recommended in the description. Yet the last bit of the installation gives the following error:

'> devtools::install_github("SoloveyMaria/community", upgrade = "always"); q()
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/msolovey/miniconda3/envs/community_tutorial/lib/R/library/stringi/libs/stringi.so':
  libicui18n.so.58: cannot open shared object file: No such file or directory
Calls: loadNamespace ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
Execution halted
make: *** [create-env] Error 1'

The environment is still generated and I can activate it and load the community package within the notebook, but the calculate_communication function throws this error:

`Error in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/home/msolovey/miniconda3/envs/community_tutorial/lib/R/library/stringi/libs/stringi.so':
  libicui18n.so.58: cannot open shared object file: No such file or directory
Traceback:

1. calculate_communication(counts = counts, anno_samples = anno_samples, 
 .     anno_cells = anno_cells, threshold_celltype_size = threshold_celltype_size, 
 .     threshold_nr_active_cells = threshold_nr_active_cells, threshold_expr = threshold_expr, 
 .     lrp_database = LR_database)
2. e_ct_g_allSamples(counts = counts, anno_cells = anno_cells, anno_interactions_allSamples = per_sample_anno_interactions, 
 .     threshold_expr = threshold_expr, verbose = verbose)
3. loadNamespace(x)
4. namespaceImport(ns, loadNamespace(i, c(lib.loc, .libPaths()), 
 .     versionCheck = vI[[i]]), from = package)
5. loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
6. namespaceImport(ns, loadNamespace(i, c(lib.loc, .libPaths()), 
 .     versionCheck = vI[[i]]), from = package)
7. loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
8. library.dynam(lib, package, package.lib)
9. dyn.load(file, DLLpath = DLLpath, ...)`

**Comment by macelik** [comment]
Hello Maria, thank you for detailed explanation. I was not able reproduce the error, however I have made a small change on the dependencies of the community package. Could you please update the package again. 

Here is how you can do it on one line.

`conda activate community_tutorial && R -e 'devtools::install_github("SoloveyMaria/community", upgrade = "always"); q()'`

**Comment by SoloveyMaria** [comment]
Hi! I now tried to re-install the package and create the new conda environment and I am getting another error:

`
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
> devtools::install_github("SoloveyMaria/community", upgrade = "always"); q()
Downloading GitHub repo SoloveyMaria/community@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/SoloveyMaria/community/tarball/HEAD' failed
`
