### ISSUE TITLE
where is the function in visualization.ipynb

### ISSUE THREAD

**Issue by huang961372045** [SoloveyMaria/community#11]
There is no mean_weights or number_interactions or plot_nrInt_vs_meanW_perCellType in community/docs/showcase_notebooks/vanGalen_Oetjen /visualization.ipynb

**Comment by huang961372045** [comment]
When I run community/docs/showcase_notebooks/vanGalen_Oetjen /visualization.ipynb, there is no function I can use as mean_weights, or number_interactions, or plot_nrInt_vs_meanW_perCellType in

**Comment by SoloveyMaria** [comment]
Dear @huang961372045 ,

Yes, indeed, we haven't included this visualisation in the van Galen Oetjen notebook so far. We'll do that shortly upon your request. In the meanwhile, you may try to replicate the side for it from the Lasry notebook.

Thank you! 
Maria

**Comment by huang961372045** [comment]
Thank you for reply.

**Comment by macelik** [comment]
@huang961372045 I have added a new visualization notebook that includes the required plots.

**Comment by huang961372045** [comment]
Hello,

Sorry to bother. Where is the visualization notebook?

Sincerely,
Ziming

**Comment by macelik** [comment]
Hello @huang961372045 ,

The notebooks are located under the [docs/showcase_notebook](https://github.com/SoloveyMaria/community/tree/main/docs/showcase_notebooks) directory. You will see three different directories there, each for a different dataset. If you are looking for the integrated vanGalen_Oetjen dataset, click [here](https://github.com/SoloveyMaria/community/tree/main/docs/showcase_notebooks/vanGalen_Oetjen) and you will find the communication and visualization notebooks. However, if you are looking for the preprocessing notebooks, they are located in a different repository, which you can find [here](https://github.com/colomemaria/community-paper).

Let me know if you need further assistance.

Best,
Muhammet

**Comment by huang961372045** [comment]
Dear Muhammet,

Thank you for your replt. I will first replicate the  [visualization.ipynb](https://github.com/SoloveyMaria/community/blob/main/docs/showcase_notebooks/vanGalen_Oetjen/visualization.ipynb).

However, I still need the function like: mean_weights, or number_interactions, or plot_nrInt_vs_meanW_perCellType. I wonder if I can use these function.

Sincerely,
Huang

**Comment by macelik** [comment]
You can load the visualization functions by running `data("visualization_functions")`. These functions should be available if you load them this way.

After that, you should be able to run, for example, `mean_weights(interactions)`. If you'd like to see the code of the function to understand what it does, you can call it without any parameters and without parentheses, `mean_weights`, and it should print out the function. Does this help?

Best,
Muhammet

**Comment by huang961372045** [comment]
Dear Muhammet,

Thank you very much. I will try.

Sincerely,
Huang
