### ISSUE TITLE
could not create the environment on a windows PC with different default conda environments directory, and PC with restrictions in redirectiong to some web services

### ISSUE THREAD

**Issue by MariiaBash** [SoloveyMaria/community#3]
I followed the instructions and ran install_windows.bat on my lab computer multiple times. Each time, it downloaded Conda and exited without any errors. However, I couldn't proceed past this step. The script consistently downloaded Conda and then exited. Meanwhile, conda was already downloaded after the fist attempt of running install_windows.bat: 
![image](https://github.com/SoloveyMaria/community/assets/135337166/847c5b64-3361-46b3-a82f-c7200a5899b7)

**Comment by MariiaBash** [comment]
I replaced the path in the install_windows.bat file with the actual path of all conda environments. It helped, conda attempted to create an environment. But then the following error occured and script exited:
![image](https://github.com/SoloveyMaria/community/assets/135337166/1a42246e-b643-482c-8c21-79226e9f95b2)

**Comment by macelik** [comment]
Hi Maria,

Thank you for using the tool and providing feedback. I appreciate your patience with the issue you encountered. To address the problem, I suggest installing mamba in the base environment of conda. It's possible that the institute's network may not have a connection to the web services used by conda.

Here are the steps to follow:

1. Activate the conda base environment by running the command `conda activate`.
2. Install mamba by running `conda install -c conda-forge mamba`.

If you still experience difficulties, please let me know. I'm here to help and provide further assistance.

Thank you for your understanding.

**Comment by MariiaBash** [comment]
Thank you for feedback. I attempted to run these commands several times, and unfortunately it still cannot connect to conda web services. I  think that the problem could really be that the institution may block redirecting to some websites.
![image](https://github.com/SoloveyMaria/community/assets/135337166/fceddcf1-60ea-4b9a-9468-9cebdb56e9c7)

**Comment by MariiaBash** [comment]
C:\Windows\system32>conda activate

(base) C:\Windows\system32>conda install -c conda-forge mamba
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/current_repodata.json>Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https//conda.anaconda.org/conda-forge/win-64'



(base) C:\Windows\system32>curl https://conda.anaconda.org/conda-forge/win-64/current_repodata.json
curl: (28) Failed to connect to conda.anaconda.org port 443 after 43076 ms: Couldn't connect to server

(base) C:\Windows\system32>which conda
Der Befehl "which" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

(base) C:\Windows\system32>where conda
C:\Users\mabashae\AppData\Local\miniconda3\Library\bin\conda.bat
C:\Users\mabashae\AppData\Local\miniconda3\Scripts\conda.exe
C:\Users\mabashae\AppData\Local\miniconda3\condabin\conda.bat

(base) C:\Windows\system32>

**Comment by MariiaBash** [comment]
I tryed running install_windows.bat on a computer disconnected from the lab network. It successfullly installed conda and created the community2 environment. But it did not open the jupyter notebook but just exited.
I then ran the following command and also searched for environments, and it found some:
![image](https://github.com/SoloveyMaria/community/assets/135337166/28e94bd3-9611-46d2-bb99-096eb6ac30bb)

I changed community_tutorial to community2 in the install_windows.bat file.  Please note to make the name of the environment consistent in the install_windows.bat file. Now it is creating the environment again: 
![image](https://github.com/SoloveyMaria/community/assets/135337166/e59cb1c2-103f-45f3-84fa-265ebd42a116)
 After that, it all worked and the Jupyter notebook successfully opened. I could also open some files there.
