### ISSUE TITLE
Error in utils::download.file(url, path, method = method, quiet = quiet,  :    download from 'https://api.github.com/repos/SoloveyMaria/community/tarball/HEAD' failed

### ISSUE THREAD

**Issue by SoloveyMaria** [SoloveyMaria/community#4]
Hi I am trying to create the community environment and am having the following error popping up:

```
devtools::install_github("SoloveyMaria/community", upgrade = "always")
Downloading GitHub repo SoloveyMaria/community@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/SoloveyMaria/community/tarball/HEAD' failed
```

**Comment by macelik** [comment]
Hello Maria,

It appears that you are experiencing a connection problem. If you would like to confirm this, you can execute the following commands in R:

`fn <- "https://api.github.com/repos/SoloveyMaria/community/tarball/HEAD"`

`download.file(fn, destfile = "tmp.tar.gz")`

This should result in a Timeout error.

To resolve this issue, you have a couple of options. First, you can clone the repository to your local machine using the following command:


`git clone https://github.com/SoloveyMaria/community.git`

Alternatively, you can download the zip file by clicking [here](https://github.com/SoloveyMaria/community/archive/refs/heads/main.zip) and then unzip it. After unzipping the file, you can install it in R by running the following command. Please make sure to execute this command in the directory where you cloned or unzipped the "community" folder.

`devtools::install("community")`
