### ISSUE TITLE
Samples with very low frequencies of certain cell types

### ISSUE THREAD

**Issue by VerenaPass** [SoloveyMaria/community#6]
Dear Maria,

When annotating cell types in our scRNA dataset I realised that our samples do not contain many different cell type populations. We have around 60% B cells (healthy or malignant), 25% of CD4+ T cells and 12-15% CD8+ T cells. The other cell populations (NK, DC, Monocytes..) are less than 1% each. 
Would this be enough for Community analysis? 

Best,

Verena

**Comment by SoloveyMaria** [comment]
Hi Verena,

You don't have to annotate the malignant B cells in any special way, you can put them as the B cell category even if there is a mixture of malignant B cells and a small rest of the healthy B cells in your tumor samples, the algorithm will "notice" that there are two populations by checking the "active fraction" component.

Best,
Maria
