### ISSUE TITLE
Do I need to annotate if cells are healthy or malignant?

### ISSUE THREAD

**Issue by VerenaPass** [SoloveyMaria/community#7]
Dear Maria,

When I annotate the cell type I’ll have both healthy and malignant B cells in the samples. Do I need to specify that or simply indicate B-cells?
Thanks!

Verena

**Comment by SoloveyMaria** [comment]
Hi Verena,

You don't have to annotate the malignant B cells in any special way, you can put them as the B cell category even if there is a mixture of malignant B cells and a small rest of the healthy B cells in your tumor samples, the algorithm will "notice" that there are two populations by checking the "active fraction" component.

Best,
Maria
