### ISSUE TITLE
Warning about mouse genes

### ISSUE THREAD

**Issue by mrichter23** [SoloveyMaria/community#8]
Hi! If you have mouse data (and mouse gene names) community does not produce results because the database is based on human gene symbols. Could there be an internal function to convert from mouse to human symbols? Or at least a warning would be great :) 
Thank you!

**Comment by macelik** [comment]
Hello there, 

We have just included mouse database,  you can load it as `data(LR_database_mouse)`. This addition is based on one-to-one orthologs identified through NCBI's HomoloGene database and the Ensembl database via biomaRt.
