### ISSUE TITLE
"_" are not allowed in cell type names

### ISSUE THREAD

**Issue by mrichter23** [SoloveyMaria/community#9]
Hi! Community is great but it doesn't run if the cell type names in the data contain underscores ("_"). The error message is quite cryptic. It would be great if there was a non-cryptic warning or if "_" could directly internally be converted to "-"

**Comment by macelik** [comment]
Hello there, 

Thanks for the feedback. We convert underscores in the celltypes to "-" and then also raise a warning for the user.

Best,
M
